export const ADD_CART = "ADD_CART";
export const DELETE_CART = "DELETE_CART";
export const INC_CART_ITEM_COUNTER = "INC_CART_ITEM_COUNTER";
export const DEC_CART_ITEM_COUNTER = "DEC_CART_ITEM_COUNTER";

export const CART_OPEN = "CART_OPEN";
export const CART_CLOSE = "CART_CLOSE";

export const INC_CART_LIST_COUNTER = "INC_CART_LIST_COUTER";
export const DEC_CART_LIST_COUNTER = "DEC_CART_LIST_COUNTER";
